webtalk_init -webtalk_dir D:/Courses-main/CS145 计算机系统结构实验/lab06/lab06.sim/sim_1/behav/xsim/xsim.dir/single_cycle_cpu_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 26 14:47:33 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5eb89a93-39a5-44ad-9a68-f8d719636dd7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7558b1b0dc3f4c769b48c9417968c178" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "13" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "132 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "12 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "135" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "26" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "51428_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1962309295 -regid "" -xml D:/Courses-main/CS145 计算机系统结构实验/lab06/lab06.sim/sim_1/behav/xsim/xsim.dir/single_cycle_cpu_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Courses-main/CS145 计算机系统结构实验/lab06/lab06.sim/sim_1/behav/xsim/xsim.dir/single_cycle_cpu_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Courses-main/CS145 计算机系统结构实验/lab06/lab06.sim/sim_1/behav/xsim/xsim.dir/single_cycle_cpu_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
